
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Skyline DataMiner Deploy Action
        uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1.0.12
        with:
            api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
            solution-path: AutomationScript.sln
            artifact-name: EmpowerHelloWorld
            version: 1.0.1
            build-number: ${{ github.run_number }}
